name: Docker Build

on:
 push:
   branches:
     - lab-3-star ## ветка(и), для которой ниже создается job при push'e
   paths:
     - "API/**" ## папка, для которой отслеживаются пуши

     
jobs:
 build:
   runs-on: self-hosted ## указываем, что сборку запускам на нашей машине, которую подклюичли к гиту

   defaults:
     run:
       working-directory: "/API" ## базовая директория

   steps:
     - name: Checkout Repository ## доступ к репозиторию
       uses: actions/checkout@v2


     - name: import-secrets
       uses: hashicorp/vault-action@v2
       with:
         url: http://127.0.0.1:8200
         tlsSkipVerify: true
         token: ${{ secrets.VAULT_TOKEN }} #в секрктах гитхаба находится токен, который получили после создания токена
         secrets: |
          secret/data/docker * | DOCKERHUB_

     - name: docker-hub-login
       uses: docker/login-action@v3
       with:
         username: ${{ env.DOCKERHUB_USERNAME }}
         password: ${{ env.dockerhub_PASSWORD }}
    
     - name: Docker pushing ##вход в учетную запись dockerhub, куда будет зугружен собранный образ на dockerhub
       uses: docker/build-push-action@v5
       with:
         context: "./API/" ##Путь к папке с проектом для сборки
         push: true
         tags: ungadult/api:latest
